version: "3.7"

services:
  template_db:
    image: mariadb:10
    restart: "no"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_USER_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
