version: "3.7"

services:
  template_nginx:
    image: nginx:latest
    restart: "no"
    environment:
      TZ: Europe/Berlin
    ports:
      - 80:80
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/conf.d/default.conf:ro
      - ${APP_PATH_RELATIVE_FROM_DOCKER_FOLDER}/build:/usr/share/nginx/html:ro
    depends_on:
      - template_backend
  template_backend:
    build: ./node-pm2-runtime/18
    restart: "no"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=${ENVIRONMENT}
    volumes:
      - ${APP_PATH_RELATIVE_FROM_DOCKER_FOLDER}:/home/node/app:rw
    depends_on:
      - template_db
    command:
      - "pm2-runtime"
      - ${PM2_CONFIG}
  template_db:
    image: mariadb:10
    restart: "no"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_USER_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
